### ISSUE TITLE
Single item page

### ISSUE THREAD

**Issue by aghimohamad** [ReCoded-Org/lets-share-capstone-project#33]
**Task title**
Single item page

**Task description**

- create the single item page which includes information about the item and a list of the most related items 
- it should be created using the dynamic routing method provided by the next.js framework

**Subtasks**

- [ ] creating the item info section /it doesn't have to be a component since we don't use it anywhere else/
- [ ] looping through the related items array and rendering the item card component 
- [ ] setting up the dynamic route environment by write the required functions for that

**Screenshots**
## Desktop
![image](https://user-images.githubusercontent.com/87778581/182042888-daf3d768-bdce-4601-a855-edcaad8e1944.png)

## Mobile 
![image](https://user-images.githubusercontent.com/87778581/182042951-dbd16355-962b-4c45-bc99-7529d3ddbc24.png)

**Link to the component on Figma**
https://www.figma.com/file/n443l0jbDzmYrkMwPyamzT/let's-share-project?node-id=135%3A1868
