### ISSUE TITLE
Blogs page

### ISSUE THREAD

**Issue by aghimohamad** [ReCoded-Org/lets-share-capstone-project#35]
**Task title**
 Blogs page

**Task description**
create a page that renders the blogs 

**Subtasks**
- [ ] create a blog card component 
- [ ] create an array with mock data and loop on it to render the blog component on each item
- [ ] you can use the blogCard component  - already created - with the small screens

**Screenshots**
## Desktop 
![image](https://user-images.githubusercontent.com/87778581/182189522-0fd9ab1e-0083-4ff8-a778-f3facdd7cdc7.png)

## Mobile 
![image](https://user-images.githubusercontent.com/87778581/182189676-5adcad5b-f2f5-4fba-b7b6-441611015151.png)

**Link to the component on Figma**
Put the link here
https://www.figma.com/file/n443l0jbDzmYrkMwPyamzT/let's-share-project?node-id=10%3A3
