### ISSUE TITLE
creating the authentication

### ISSUE THREAD

**Issue by aghimohamad** [ReCoded-Org/lets-share-capstone-project#63]
**Task title**
create the authentication
**Task description**
create the authentication for the website using Facebook - Gmail -Email

**Subtasks**
- [ ] work on Facebook authentication
- [ ] work on Gmail authentication
- [ ] work on Email authentication
